"""The examples in docs/examples.md run, print what the page shows, and match Stata's output.

The page is generated by ``tests/reference/build_docs_examples.py``.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import pytest
from test_stata_parity import _lines, _same_line

sys.path.insert(0, str(Path(__file__).parent / "reference"))
from build_docs_examples import run  # noqa: E402

PAGE = Path(__file__).parents[1] / "docs" / "examples.md"
BLOCK = re.compile(
    r"```python\n(?P<code>.*?)\n```.*?```text\n(?P<output>.*?)\n```.*?"
    r'\?\?\? quote "Stata output"\n\n    ```text\n(?P<stata>.*?)\n    ```',
    re.S,
)
EXAMPLES = [m.groupdict() for m in BLOCK.finditer(PAGE.read_text(encoding="utf-8"))]


def test_examples_found():
    assert len(EXAMPLES) >= 10


@pytest.mark.parametrize("ex", EXAMPLES, ids=[f"example{i + 1}" for i in range(len(EXAMPLES))])
def test_example(ex):
    printed = run(ex["code"])
    assert printed == ex["output"], "docs/examples.md is out of date: run tests/reference/build_docs_examples.py"
    stata = "\n".join(line[4:] for line in ex["stata"].split("\n"))
    py, st = _lines(printed), _lines(stata)
    assert len(py) == len(st)
    for p, s in zip(py, st):
        assert _same_line(p, s), f"\npython: {p}\nstata:  {s}"


def test_home_page_example():
    page = (PAGE.parent / "index.md").read_text(encoding="utf-8")
    code = re.search(r"```python\n(.*?)\n```", page, re.S).group(1)
    shown = re.search(r"```text\n(.*?)\n```", page, re.S).group(1)
    assert run(code) == shown
